### ISSUE TITLE
Clicking on profile causes crash (friends-since v1.0.2)

### ISSUE THREAD

**Issue by raffel080108** [doggybootsy/BDPlugins#11]
Related to #9 and #10
Clicking on discord profile causes discord to freeze and then crash. I tested this with the plugin being the only one that is loaded

The console log spams this Warn about 20 times or so:
<details>
  <summary>Warn log message</summary>

```
71586.bec48eead506f88a39f4.js:1 Trying to remove a child that doesn't exist
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
(anonymous) @ VM22559 43455.8c79ce3e1753b38de4a4.js:23
value @ 2160.5b1de8a086b42fe36070.js:1
value @ 2160.5b1de8a086b42fe36070.js:1
value @ 2160.5b1de8a086b42fe36070.js:1
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
oq @ 2160.5b1de8a086b42fe36070.js:12
oQ @ 2160.5b1de8a086b42fe36070.js:12
(anonymous) @ 2160.5b1de8a086b42fe36070.js:12
sY @ 2160.5b1de8a086b42fe36070.js:12
sM @ 2160.5b1de8a086b42fe36070.js:12
r6 @ 2160.5b1de8a086b42fe36070.js:12
(anonymous) @ 2160.5b1de8a086b42fe36070.js:12
```
</details>

after which discord crashes and prints this Error log message:
<details>
  <summary>Error log message</summary>

```
71586.bec48eead506f88a39f4.js:1 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sx (2160.5b1de8a086b42fe36070.js:12:931402)
    at a0 (2160.5b1de8a086b42fe36070.js:12:904921)
    at 71586.bec48eead506f88a39f4.js:1:530659
    at l (71586.bec48eead506f88a39f4.js:1:531119)
    at 71586.bec48eead506f88a39f4.js:1:530048
    at aS (2160.5b1de8a086b42fe36070.js:12:899609)
    at ol (2160.5b1de8a086b42fe36070.js:12:909928)
    at u (2160.5b1de8a086b42fe36070.js:12:956910)
    at sB (2160.5b1de8a086b42fe36070.js:12:937835)
    at 2160.5b1de8a086b42fe36070.js:12:937701
    at sF (2160.5b1de8a086b42fe36070.js:12:937709)
    at sM (2160.5b1de8a086b42fe36070.js:12:934794)
    at r6 (2160.5b1de8a086b42fe36070.js:12:883484)
    at 2160.5b1de8a086b42fe36070.js:12:932332
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
(anonymous) @ VM22559 43455.8c79ce3e1753b38de4a4.js:23
oe @ 2160.5b1de8a086b42fe36070.js:12
a.componentDidCatch.n.callback @ 2160.5b1de8a086b42fe36070.js:12
iW @ 2160.5b1de8a086b42fe36070.js:12
oX @ 2160.5b1de8a086b42fe36070.js:12
e @ 2160.5b1de8a086b42fe36070.js:12
(anonymous) @ 2160.5b1de8a086b42fe36070.js:12
sY @ 2160.5b1de8a086b42fe36070.js:12
sM @ 2160.5b1de8a086b42fe36070.js:12
r6 @ 2160.5b1de8a086b42fe36070.js:12
(anonymous) @ 2160.5b1de8a086b42fe36070.js:12
```
</details>

Something that I found intersting is that from my testing, if you go to the "Friends", "Nitro" or "Shop" tab in the DMs section you can open the profile popout just fine and if you go back to a chat tab afterwards it doesn't crash anymore. 
In this case the log will instead print the previous warning message 10-11 times or so and then afterwards it will print the following warning twice every time you close the profile popout:
<details>
  <summary>Warn log message</summary>

```
71586.bec48eead506f88a39f4.js:1 [ComponentDispatchUtils] ComponentDispatch.subscribe: Attempting to add a duplicate listener POPOUT_CLOSE
t.<computed> @ 71586.bec48eead506f88a39f4.js:1
(anonymous) @ VM23114 43455.8c79ce3e1753b38de4a4.js:23
(anonymous) @ 71586.bec48eead506f88a39f4.js:1
(anonymous) @ 71586.bec48eead506f88a39f4.js:1
subscribe @ 71586.bec48eead506f88a39f4.js:1
setupShowPopout @ 71586.bec48eead506f88a39f4.js:1
componentDidUpdate @ 71586.bec48eead506f88a39f4.js:1
oX @ 2160.5b1de8a086b42fe36070.js:12
e @ 2160.5b1de8a086b42fe36070.js:12
e @ 2160.5b1de8a086b42fe36070.js:12
(anonymous) @ 2160.5b1de8a086b42fe36070.js:12
sY @ 2160.5b1de8a086b42fe36070.js:12
sM @ 2160.5b1de8a086b42fe36070.js:12
r6 @ 2160.5b1de8a086b42fe36070.js:12
(anonymous) @ 2160.5b1de8a086b42fe36070.js:12
```
</details>

But discord will not crash in this state, so the crash seems to be related to initially having a chat page open when clicking the profile popout.

**Comment by thehamish555** [comment]
Bump this, no longer works entirely after discord update

**Comment by doggybootsy** [comment]
Fixed in latest push
